---
# Source: konfigurator/templates/operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: konfigurator
    group: com.stakater.platform
    provider: stakater
    version: v0.0.21
    chart: "konfigurator-v0.0.21"
    release: "konfigurator"
    heritage: "Tiller"
  name: konfigurator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: konfigurator
      group: com.stakater.platform
      provider: stakater
  template:
    metadata:
      labels:
        app: konfigurator
        group: com.stakater.platform
        provider: stakater
    spec:
      containers:
        - name: konfigurator
          image: "stakater/konfigurator:v0.0.21"
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - Konfigurator
          env:
            - name: OPERATOR_NAME
              value: "konfigurator"
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
      serviceAccountName: konfigurator

