builds:
- env:
  - CGO_ENABLED=0
  goos:
  - windows
  - darwin
  - linux
  goarch:
  - 386
  - amd64
  - arm
  - arm64
archives:
- name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
snapshot:
  name_template: "{{ .Tag }}-next"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
env_files:
  github_token: /home/jenkins/.apitoken/hub