
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-konfigurator-stakater-com-v1alpha1-konfiguratortemplate
  failurePolicy: Fail
  name: mkonfiguratortemplate.kb.io
  rules:
  - apiGroups:
    - konfigurator.stakater.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - konfiguratortemplates
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-konfigurator-stakater-com-v1alpha1-konfiguratortemplate
  failurePolicy: Fail
  name: vkonfiguratortemplate.kb.io
  rules:
  - apiGroups:
    - konfigurator.stakater.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - konfiguratortemplates
  sideEffects: None
