# permissions for end users to view konfiguratortemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: konfiguratortemplate-viewer-role
rules:
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - konfiguratortemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - konfiguratortemplates/status
  verbs:
  - get
