# permissions for end users to edit podmetadatainjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmetadatainjector-editor-role
rules:
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - podmetadatainjectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - podmetadatainjectors/status
  verbs:
  - get
