# permissions for end users to view podmetadatainjectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podmetadatainjector-viewer-role
rules:
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - podmetadatainjectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - konfigurator.stakater.com
  resources:
  - podmetadatainjectors/status
  verbs:
  - get
