---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
  {{- include "konfigurator.labels.stakater" . | nindent 4 }}
  {{- include "konfigurator.labels.chart" . | nindent 4 }}
  name: {{ template "konfigurator.name" . }}-{{ .Release.Namespace }}-cluster-role-binding
subjects:
- kind: ServiceAccount
  name: {{ template "konfigurator.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "konfigurator.name" . }}-{{ .Release.Namespace }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
