{{- if .Values.deployCRD }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: konfiguratortemplates.konfigurator.stakater.com
spec:
  group: konfigurator.stakater.com
  names:
    kind: KonfiguratorTemplate
    listKind: KonfiguratorTemplateList
    plural: konfiguratortemplates
    singular: konfiguratortemplate
  scope: Namespaced
  version: v1alpha1
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmetadatainjectors.konfigurator.stakater.com
spec:
  group: konfigurator.stakater.com
  names:
    kind: PodMetadataInjector
    listKind: PodMetadataInjectorList
    plural: podmetadatainjectors
    singular: podmetadatainjector
  scope: Namespaced
  version: v1alpha1
{{- end }}