apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "konfigurator.labels.stakater" . | nindent 4 }}
  {{- include "konfigurator.labels.chart" . | nindent 4 }}
  name: {{ template "konfigurator.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{- include "konfigurator.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
{{- include "konfigurator.labels.selector" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ template "konfigurator.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
          - containerPort: 8080
            name: metrics
          args:
          - --enable-leader-election
          env:
          - name: OPERATOR_NAME
            value: "{{ template "konfigurator.name" . }}"
{{ toYaml .Values.env | indent 10 }}
      serviceAccountName: {{ template "konfigurator.name" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
  {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
  {{- end }}
