---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
{{- include "konfigurator.labels.stakater" . | nindent 4 }}
{{- include "konfigurator.labels.chart" . | nindent 4 }}
  name: {{ template "konfigurator.name" . }}-role-binding
  namespace: {{ .Values.namespace | default .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ template "konfigurator.name" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ template "konfigurator.name" . }}-role
  apiGroup: rbac.authorization.k8s.io

